### ISSUE TITLE
[DEV/BETA] Error reading/setting inverter model

### ISSUE THREAD

**Issue by poolski** [britkat1980/ha-addons#11]
I've been running the latest stable version of GivTCP without issues for a few months now but when trying to install the Dev/Beta releases as HA Addons, both throw errors when trying to read the inverter's settings as below.

```
2024-08-19 15:07:36,280 - startup - [INFO] - Setting up invertor: 1
Traceback (most recent call last):
  File "/app/startup.py", line 542, in <module>
    createsettingsjson(inv)
  File "/app/startup.py", line 155, in createsettingsjson
    setts["Model_"+str(inv)]= inverter_type['Model'].name.capitalize()
                              ~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

Here's the inverter model + firmware release: 
![PixelSnap 2024-08-19 at 15 11 08@2x](https://github.com/user-attachments/assets/04186599-5b1f-4a81-92e7-f5845dbd2758)

As far as I'm aware there are no newer firmware releases available.

**Comment by poolski** [comment]
I just realised that I'd submitted the issue to the wrong repo 🤦🏻
